"""Initial sources_record

Revision ID: 17cdff8379cb
Revises: 
Create Date: 2023-03-15 01:52:21.177793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cdff8379cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources_record',
    sa.Column('url', sa.String(length=10000), nullable=False),
    sa.Column('url_hash', sa.String(length=1000), nullable=False),
    sa.Column('crawl_id', sa.String(length=1000), nullable=False),
    sa.Column('shard_id', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=10000), nullable=False),
    sa.Column('status_code', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=1000), nullable=True),
    sa.Column('content_length', sa.String(length=1000), nullable=True),
    sa.Column('content_encoding', sa.String(length=1000), nullable=False),
    sa.Column('content_language', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('source_filename', sa.String(length=10000), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('olet_ftype', sa.String(length=200), nullable=True),
    sa.Column('olet_container', sa.String(length=200), nullable=True),
    sa.Column('olet_appname', sa.String(length=200), nullable=True),
    sa.Column('olet_codepage', sa.String(length=200), nullable=True),
    sa.Column('olet_author', sa.String(length=400), nullable=True),
    sa.Column('olet_encrypted', sa.String(length=200), nullable=True),
    sa.Column('olet_vba', sa.String(length=400), nullable=True),
    sa.Column('olet_xlm', sa.String(length=400), nullable=True),
    sa.Column('olet_ext_rels', sa.String(length=200), nullable=True),
    sa.Column('olet_ObjectPool', sa.String(length=200), nullable=True),
    sa.Column('olet_flash', sa.String(length=200), nullable=True),
    sa.Column('olet_python_codec', sa.String(length=200), nullable=True),
    sa.Column('olet_pass', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('exception', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('url_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources_record')
    # ### end Alembic commands ###
