"""Initial metadata model

Revision ID: d1fbae82c5fa
Revises: 17cdff8379cb
Create Date: 2023-04-11 06:11:03.232383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fbae82c5fa'
down_revision = '17cdff8379cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_record',
    sa.Column('doc_id', sa.String(length=10000), nullable=False),
    sa.Column('url', sa.String(length=10000), nullable=False),
    sa.Column('url_hash', sa.String(length=1000), nullable=False),
    sa.Column('crawl_id', sa.String(length=1000), nullable=False),
    sa.Column('shard_id', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=10000), nullable=False),
    sa.Column('geo_location', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('languages_fasttest', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('languages_autocorrect', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('doc_type', sa.String(length=1000), nullable=True),
    sa.Column('industry', sa.String(length=1000), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('num_figures', sa.Integer(), nullable=False),
    sa.Column('num_tables', sa.Integer(), nullable=False),
    sa.Column('num_table_cells', sa.Integer(), nullable=False),
    sa.Column('num_quotes', sa.Integer(), nullable=False),
    sa.Column('num_equations', sa.Integer(), nullable=False),
    sa.Column('num_sections_1', sa.Integer(), nullable=False),
    sa.Column('num_sections_2', sa.Integer(), nullable=False),
    sa.Column('num_sections_3', sa.Integer(), nullable=False),
    sa.Column('num_sections_4', sa.Integer(), nullable=False),
    sa.Column('num_sections_5', sa.Integer(), nullable=False),
    sa.Column('num_sections_6', sa.Integer(), nullable=False),
    sa.Column('num_sections_7', sa.Integer(), nullable=False),
    sa.Column('num_sections_8', sa.Integer(), nullable=False),
    sa.Column('num_sections_9', sa.Integer(), nullable=False),
    sa.Column('annotation_sources', sa.JSON(), nullable=False),
    sa.Column('form_hover_tags', sa.JSON(), nullable=True),
    sa.Column('template_name', sa.String(length=1000), nullable=True),
    sa.Column('creator_username', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_record')
    # ### end Alembic commands ###
