"""Remove sensitive info, add bytehash

Revision ID: 2de829bd1ca3
Revises: d1fbae82c5fa
Create Date: 2023-05-29 01:23:22.193645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2de829bd1ca3'
down_revision = 'd1fbae82c5fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_metadata_record',
    sa.Column('url_hash', sa.String(length=1000), nullable=False),
    sa.Column('crawl_id', sa.String(length=1000), nullable=False),
    sa.Column('sources_shard_id', sa.String(length=1000), nullable=False),
    sa.Column('annotated_shard_id', sa.String(length=1000), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('annotation_exit_msg', sa.String(length=1000), nullable=True),
    sa.Column('annotation_status', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=10000), nullable=False),
    sa.Column('filename', sa.String(length=10000), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('languages_fasttext', sa.JSON(), nullable=True),
    sa.Column('languages_autocorrect', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('top_lang', sa.String(length=1000), nullable=True),
    sa.Column('top_lang_score', sa.Float(), nullable=True),
    sa.Column('num_title', sa.Integer(), nullable=False),
    sa.Column('num_heading_1', sa.Integer(), nullable=False),
    sa.Column('num_heading_2', sa.Integer(), nullable=False),
    sa.Column('num_heading_3', sa.Integer(), nullable=False),
    sa.Column('num_heading_4', sa.Integer(), nullable=False),
    sa.Column('num_heading_5', sa.Integer(), nullable=False),
    sa.Column('num_heading_6', sa.Integer(), nullable=False),
    sa.Column('num_heading_7', sa.Integer(), nullable=False),
    sa.Column('num_heading_8', sa.Integer(), nullable=False),
    sa.Column('num_heading_9', sa.Integer(), nullable=False),
    sa.Column('num_text', sa.Integer(), nullable=False),
    sa.Column('num_list', sa.Integer(), nullable=False),
    sa.Column('num_header', sa.Integer(), nullable=False),
    sa.Column('num_footer', sa.Integer(), nullable=False),
    sa.Column('num_table_header', sa.Integer(), nullable=False),
    sa.Column('num_table_header_cell', sa.Integer(), nullable=False),
    sa.Column('num_table', sa.Integer(), nullable=False),
    sa.Column('num_table_cell', sa.Integer(), nullable=False),
    sa.Column('num_toc', sa.Integer(), nullable=False),
    sa.Column('num_bibliography', sa.Integer(), nullable=False),
    sa.Column('num_quote', sa.Integer(), nullable=False),
    sa.Column('num_equation', sa.Integer(), nullable=False),
    sa.Column('num_figure', sa.Integer(), nullable=False),
    sa.Column('num_table_caption', sa.Integer(), nullable=False),
    sa.Column('num_footnote', sa.Integer(), nullable=False),
    sa.Column('num_annotation', sa.Integer(), nullable=False),
    sa.Column('num_form_field', sa.Integer(), nullable=False),
    sa.Column('num_form_tag', sa.Integer(), nullable=False),
    sa.Column('num_table_row', sa.Integer(), nullable=False),
    sa.Column('num_table_column', sa.Integer(), nullable=False),
    sa.Column('num_table_header_row', sa.Integer(), nullable=False),
    sa.Column('annotation_sources', sa.JSON(), nullable=False),
    sa.Column('template_name', sa.String(length=1000), nullable=True),
    sa.Column('core_category', sa.String(length=1000), nullable=True),
    sa.Column('core_comments', sa.String(length=1000), nullable=True),
    sa.Column('core_content_status', sa.String(length=1000), nullable=True),
    sa.Column('core_created', sa.DateTime(), nullable=True),
    sa.Column('core_identifier', sa.String(length=1000), nullable=True),
    sa.Column('core_keywords', sa.String(length=1000), nullable=True),
    sa.Column('core_last_printed', sa.DateTime(), nullable=True),
    sa.Column('core_modified', sa.DateTime(), nullable=True),
    sa.Column('core_subject', sa.String(length=1000), nullable=True),
    sa.Column('core_title', sa.String(length=1000), nullable=True),
    sa.Column('core_version', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('page_metadata_record',
    sa.Column('page_id', sa.String(length=10000), nullable=False),
    sa.Column('url', sa.String(length=10000), nullable=False),
    sa.Column('url_hash', sa.String(length=1000), nullable=False),
    sa.Column('crawl_id', sa.String(length=1000), nullable=False),
    sa.Column('sources_shard_id', sa.String(length=1000), nullable=False),
    sa.Column('annotated_shard_id', sa.String(length=1000), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('languages_fasttext', sa.JSON(), nullable=True),
    sa.Column('top_lang', sa.String(length=1000), nullable=True),
    sa.Column('top_lang_score', sa.Float(), nullable=True),
    sa.Column('page_height', sa.Float(), nullable=False),
    sa.Column('page_width', sa.Float(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('num_title', sa.Integer(), nullable=False),
    sa.Column('num_heading_1', sa.Integer(), nullable=False),
    sa.Column('num_heading_2', sa.Integer(), nullable=False),
    sa.Column('num_heading_3', sa.Integer(), nullable=False),
    sa.Column('num_heading_4', sa.Integer(), nullable=False),
    sa.Column('num_heading_5', sa.Integer(), nullable=False),
    sa.Column('num_heading_6', sa.Integer(), nullable=False),
    sa.Column('num_heading_7', sa.Integer(), nullable=False),
    sa.Column('num_heading_8', sa.Integer(), nullable=False),
    sa.Column('num_heading_9', sa.Integer(), nullable=False),
    sa.Column('num_text', sa.Integer(), nullable=False),
    sa.Column('num_list', sa.Integer(), nullable=False),
    sa.Column('num_header', sa.Integer(), nullable=False),
    sa.Column('num_footer', sa.Integer(), nullable=False),
    sa.Column('num_table_header', sa.Integer(), nullable=False),
    sa.Column('num_table_header_cell', sa.Integer(), nullable=False),
    sa.Column('num_table', sa.Integer(), nullable=False),
    sa.Column('num_table_cell', sa.Integer(), nullable=False),
    sa.Column('num_toc', sa.Integer(), nullable=False),
    sa.Column('num_bibliography', sa.Integer(), nullable=False),
    sa.Column('num_quote', sa.Integer(), nullable=False),
    sa.Column('num_equation', sa.Integer(), nullable=False),
    sa.Column('num_figure', sa.Integer(), nullable=False),
    sa.Column('num_table_caption', sa.Integer(), nullable=False),
    sa.Column('num_footnote', sa.Integer(), nullable=False),
    sa.Column('num_annotation', sa.Integer(), nullable=False),
    sa.Column('num_form_field', sa.Integer(), nullable=False),
    sa.Column('num_form_tag', sa.Integer(), nullable=False),
    sa.Column('num_table_row', sa.Integer(), nullable=False),
    sa.Column('num_table_column', sa.Integer(), nullable=False),
    sa.Column('num_table_header_row', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('page_id', 'url')
    )
    op.drop_table('metadata_record')
    op.add_column('sources_record', sa.Column('bytehash', sa.String(length=10000), nullable=False))
    op.drop_column('sources_record', 'ip_address')
    op.drop_column('sources_record', 'olet_author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources_record', sa.Column('olet_author', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.add_column('sources_record', sa.Column('ip_address', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('sources_record', 'bytehash')
    op.create_table('metadata_record',
    sa.Column('doc_id', sa.VARCHAR(length=10000), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=10000), autoincrement=False, nullable=False),
    sa.Column('url_hash', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('crawl_id', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('shard_id', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=10000), autoincrement=False, nullable=False),
    sa.Column('geo_location', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('languages_fasttest', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('languages_autocorrect', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('doc_type', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_figures', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_tables', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_table_cells', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_quotes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_equations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_3', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_4', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_5', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_6', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_7', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_8', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_sections_9', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('annotation_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('form_hover_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('creator_username', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('doc_id', name='metadata_record_pkey')
    )
    op.drop_table('page_metadata_record')
    op.drop_table('doc_metadata_record')
    # ### end Alembic commands ###
