# possible sources of colorization decision

ANNOTATION_BUILTIN = "builtin"
ANNOTATION_XML_PATTERN = "xml_pattern"
ANNOTATION_CONTENT_AWARE_HEURISTIC = "content_aware_heuristic"
ANNOTATION_BODY_HEADING_HEURISTIC_USINGBUILTIN = "body_heading_heuristic_usingbuiltin"
ANNOTATION_BODY_HEADING_HEURISTIC_BASE = "body_heading_heuristic_base"

DECISION_SOURCES = [
    ANNOTATION_BUILTIN,
    ANNOTATION_XML_PATTERN,
    ANNOTATION_CONTENT_AWARE_HEURISTIC,
    ANNOTATION_BODY_HEADING_HEURISTIC_USINGBUILTIN,
    ANNOTATION_BODY_HEADING_HEURISTIC_BASE
]
# builtins vs heuristics
BUILTIN_SOURCES = [
    ANNOTATION_BUILTIN,
    ANNOTATION_XML_PATTERN
]
HEURISTIC_SOURCES = [
    ANNOTATION_CONTENT_AWARE_HEURISTIC,
    ANNOTATION_BODY_HEADING_HEURISTIC_USINGBUILTIN,
    ANNOTATION_BODY_HEADING_HEURISTIC_BASE,
]
