TOTAL_BASE_LABELS = 31
LABEL_NUMS = [i for i in range(0, TOTAL_BASE_LABELS)]

ENTITY_TITLE_NAME = "title"
ENTITY_TITLE_ID = 0

ENTITY_HEADING_1_NAME = "heading_1"
ENTITY_HEADING_1_ID = 1

ENTITY_HEADING_2_NAME = "heading_2"
ENTITY_HEADING_2_ID = 2

ENTITY_HEADING_3_NAME = "heading_3"
ENTITY_HEADING_3_ID = 3

ENTITY_HEADING_4_NAME = "heading_4"
ENTITY_HEADING_4_ID = 4

ENTITY_HEADING_5_NAME = "heading_5"
ENTITY_HEADING_5_ID = 5

ENTITY_HEADING_6_NAME = "heading_6"
ENTITY_HEADING_6_ID = 6

ENTITY_HEADING_7_NAME = "heading_7"
ENTITY_HEADING_7_ID = 7

ENTITY_HEADING_8_NAME = "heading_8"
ENTITY_HEADING_8_ID = 8

ENTITY_HEADING_9_NAME = "heading_9"
ENTITY_HEADING_9_ID = 9

ENTITY_TEXT_NAME = "text"
ENTITY_TEXT_ID = 10

ENTITY_LIST_NAME = "list"
ENTITY_LIST_ID = 11

ENTITY_HEADER_NAME = "header"
ENTITY_HEADER_ID = 12

ENTITY_FOOTER_NAME = "footer"
ENTITY_FOOTER_ID = 13

ENTITY_TABLE_HEADER_NAME = "table_header"
ENTITY_TABLE_HEADER_ID = 14

ENTITY_TABLE_HEADER_CELL_NAME = "table_header_cell"
ENTITY_TABLE_HEADER_CELL_ID = 15

ENTITY_TABLE_NAME = "table"
ENTITY_TABLE_ID = 16

ENTITY_TABLE_CELL_NAME = "table_cell"
ENTITY_TABLE_CELL_ID = 17

ENTITY_TOC_NAME = "toc"
ENTITY_TOC_ID = 18

ENTITY_BIBLIOGRAPHY_NAME = "bibliography"
ENTITY_BIBLIOGRAPHY_ID = 19

ENTITY_QUOTE_NAME = "quote"
ENTITY_QUOTE_ID = 20

ENTITY_EQUATION_NAME = "equation"
ENTITY_EQUATION_ID = 21

ENTITY_FIGURE_NAME = "figure"
ENTITY_FIGURE_ID = 22

ENTITY_TABLE_CAPTION_NAME = "table_caption"
ENTITY_TABLE_CAPTION_ID = 23

ENTITY_FOOTNOTE_NAME = "footnote"
ENTITY_FOOTNOTE_ID = 24

ENTITY_ANNOTATION_NAME = "annotation"
ENTITY_ANNOTATION_ID = 25

ENTITY_FORM_FIELD_NAME = "form_field"
ENTITY_FORM_FIELD_ID = 26

ENTITY_FORM_TAG_NAME = "form_tag"
ENTITY_FORM_TAG_ID = 27

ENTITY_TABLE_ROW_NAME = "table_row"
ENTITY_TABLE_ROW_ID = 28

ENTITY_TABLE_COLUMN_NAME = "table_column"
ENTITY_TABLE_COLUMN_ID = 29

ENTITY_TABLE_HEADER_ROW_NAME = "table_header_row"
ENTITY_TABLE_HEADER_ROW_ID = 30

# put all entity names in a list
ALL_ENTITY_NAMES = [
    eval(entity_name_var)
    for entity_name_var in dir()
    if (
        entity_name_var.startswith("ENTITY_")
        and entity_name_var.endswith("_NAME")
        and isinstance(eval(entity_name_var), str)
    )
]

# put all entity ids in a list
ALL_ENTITY_IDS = [
    eval(entity_id_var)
    for entity_id_var in dir()
    if (
        entity_id_var.startswith("ENTITY_")
        and entity_id_var.endswith("_ID")
        and isinstance(eval(entity_id_var), int)
    )
]

ENTITY_ID_TO_NAME = {
    ENTITY_TITLE_ID: ENTITY_TITLE_NAME,
    ENTITY_HEADING_1_ID: ENTITY_HEADING_1_NAME,
    ENTITY_HEADING_2_ID: ENTITY_HEADING_2_NAME,
    ENTITY_HEADING_3_ID: ENTITY_HEADING_3_NAME,
    ENTITY_HEADING_4_ID: ENTITY_HEADING_4_NAME,
    ENTITY_HEADING_5_ID: ENTITY_HEADING_5_NAME,
    ENTITY_HEADING_6_ID: ENTITY_HEADING_6_NAME,
    ENTITY_HEADING_7_ID: ENTITY_HEADING_7_NAME,
    ENTITY_HEADING_8_ID: ENTITY_HEADING_8_NAME,
    ENTITY_HEADING_9_ID: ENTITY_HEADING_9_NAME,
    ENTITY_TEXT_ID: ENTITY_TEXT_NAME,
    ENTITY_LIST_ID: ENTITY_LIST_NAME,
    ENTITY_HEADER_ID: ENTITY_HEADER_NAME,
    ENTITY_FOOTER_ID: ENTITY_FOOTER_NAME,
    ENTITY_TABLE_HEADER_ID: ENTITY_TABLE_HEADER_NAME,
    ENTITY_TABLE_HEADER_CELL_ID: ENTITY_TABLE_HEADER_CELL_NAME,
    ENTITY_TABLE_ID: ENTITY_TABLE_NAME,
    ENTITY_TABLE_CELL_ID: ENTITY_TABLE_CELL_NAME,
    ENTITY_TOC_ID: ENTITY_TOC_NAME,
    ENTITY_BIBLIOGRAPHY_ID: ENTITY_BIBLIOGRAPHY_NAME,
    ENTITY_QUOTE_ID: ENTITY_QUOTE_NAME,
    ENTITY_EQUATION_ID: ENTITY_EQUATION_NAME,
    ENTITY_FIGURE_ID: ENTITY_FIGURE_NAME,
    ENTITY_TABLE_CAPTION_ID: ENTITY_TABLE_CAPTION_NAME,
    ENTITY_FOOTNOTE_ID: ENTITY_FOOTNOTE_NAME,
    ENTITY_ANNOTATION_ID: ENTITY_ANNOTATION_NAME,
    ENTITY_FORM_FIELD_ID: ENTITY_FORM_FIELD_NAME,
    ENTITY_FORM_TAG_ID: ENTITY_FORM_TAG_NAME,
    ENTITY_TABLE_ROW_ID: ENTITY_TABLE_ROW_NAME,
    ENTITY_TABLE_COLUMN_ID: ENTITY_TABLE_COLUMN_NAME,
    ENTITY_TABLE_HEADER_ROW_ID: ENTITY_TABLE_HEADER_ROW_NAME,
}

ENTITY_NAME_TO_ID = {}
for k, v in ENTITY_ID_TO_NAME.items():
    ENTITY_NAME_TO_ID[v] = k
