BUILTIN_STYLES = [
    "normal",
    "heading 1",
    "heading 2",
    "heading 3",
    "heading 4",
    "heading 5",
    "heading 6",
    "heading 7",
    "heading 8",
    "heading 9",
    "index 1",
    "index 2",
    "index 3",
    "index 4",
    "index 5",
    "index 6",
    "index 7",
    "index 8",
    "index 9",
    "toc 1",
    "toc 2",
    "toc 3",
    "toc 4",
    "toc 5",
    "toc 6",
    "toc 7",
    "toc 8",
    "toc 9",
    "normal indent",
    "footnote text",
    "annotation text",
    "header",
    "footer",
    "index heading",
    "caption",
    "table of figures",
    "envelope address",
    "envelope return",
    "footnote reference",
    "annotation reference",
    "line number",
    "page number",
    "endnote reference",
    "endnote text",
    "table of authorities",
    "macro",
    "toa heading",
    "list",
    "list bullet",
    "list number",
    "list 2",
    "list 3",
    "list 4",
    "list 5",
    "list bullet 2",
    "list bullet 3",
    "list bullet 4",
    "list bullet 5",
    "list number 2",
    "list number 3",
    "list number 4",
    "list number 5",
    "title",
    "closing",
    "signature",
    "default paragraph font",
    "body text",
    "body text indent",
    "list continue",
    "list continue 2",
    "list continue 3",
    "list continue 4",
    "list continue 5",
    "message header",
    "subtitle",
    "salutation",
    "date",
    "body text first indent",
    "body text first indent 2",
    "note heading",
    "body text 2",
    "body text 3",
    "body text indent 2",
    "body text indent 3",
    "block text",
    "hyperlink",
    "followedhyperlink",
    "strong",
    "emphasis",
    "document map",
    "plain text",
    "e-mail signature",
    "html top of form",
    "html bottom of form",
    "normal (web)",
    "html acronym",
    "html address",
    "html cite",
    "html code",
    "html definition",
    "html keyboard",
    "html preformatted",
    "html sample",
    "html typewriter",
    "html variable",
    "normal table",
    "annotation subject",
    "no list",
    "outline list 1",
    "outline list 2",
    "outline list 3",
    "table simple 1",
    "table simple 2",
    "table simple 3",
    "table classic 1",
    "table classic 2",
    "table classic 3",
    "table classic 4",
    "table colorful 1",
    "table colorful 2",
    "table colorful 3",
    "table columns 1",
    "table columns 2",
    "table columns 3",
    "table columns 4",
    "table columns 5",
    "table grid 1",
    "table grid 2",
    "table grid 3",
    "table grid 4",
    "table grid 5",
    "table grid 6",
    "table grid 7",
    "table grid 8",
    "table list 1",
    "table list 2",
    "table list 3",
    "table list 4",
    "table list 5",
    "table list 6",
    "table list 7",
    "table list 8",
    "table 3d effects 1",
    "table 3d effects 2",
    "table 3d effects 3",
    "table contemporary",
    "table elegant",
    "table professional",
    "table subtle 1",
    "table subtle 2",
    "table web 1",
    "table web 2",
    "table web 3",
    "balloon text",
    "table grid",
    "table theme",
    "placeholder text",
    "no spacing",
    "light shading",
    "light list",
    "light grid",
    "medium shading 1",
    "medium shading 2",
    "medium list 1",
    "medium list 2",
    "medium grid 1",
    "medium grid 2",
    "medium grid 3",
    "dark list",
    "colorful shading",
    "colorful list",
    "colorful grid",
    "light shading accent 1",
    "light list accent 1",
    "light grid accent 1",
    "medium shading 1 accent 1",
    "medium shading 2 accent 1",
    "medium list 1 accent 1",
    "revision",
    "list paragraph",
    "quote",
    "intense quote",
    "medium list 2 accent 1",
    "medium grid 1 accent 1",
    "medium grid 2 accent 1",
    "medium grid 3 accent 1",
    "dark list accent 1",
    "colorful shading accent 1",
    "colorful list accent 1",
    "colorful grid accent 1",
    "light shading accent 2",
    "light list accent 2",
    "light grid accent 2",
    "medium shading 1 accent 2",
    "medium shading 2 accent 2",
    "medium list 1 accent 2",
    "medium list 2 accent 2",
    "medium grid 1 accent 2",
    "medium grid 2 accent 2",
    "medium grid 3 accent 2",
    "dark list accent 2",
    "colorful shading accent 2",
    "colorful list accent 2",
    "colorful grid accent 2",
    "light shading accent 3",
    "light list accent 3",
    "light grid accent 3",
    "medium shading 1 accent 3",
    "medium shading 2 accent 3",
    "medium list 1 accent 3",
    "medium list 2 accent 3",
    "medium grid 1 accent 3",
    "medium grid 2 accent 3",
    "medium grid 3 accent 3",
    "dark list accent 3",
    "colorful shading accent 3",
    "colorful list accent 3",
    "colorful grid accent 3",
    "light shading accent 4",
    "light list accent 4",
    "light grid accent 4",
    "medium shading 1 accent 4",
    "medium shading 2 accent 4",
    "medium list 1 accent 4",
    "medium list 2 accent 4",
    "medium grid 1 accent 4",
    "medium grid 2 accent 4",
    "medium grid 3 accent 4",
    "dark list accent 4",
    "colorful shading accent 4",
    "colorful list accent 4",
    "colorful grid accent 4",
    "light shading accent 5",
    "light list accent 5",
    "light grid accent 5",
    "medium shading 1 accent 5",
    "medium shading 2 accent 5",
    "medium list 1 accent 5",
    "medium list 2 accent 5",
    "medium grid 1 accent 5",
    "medium grid 2 accent 5",
    "medium grid 3 accent 5",
    "dark list accent 5",
    "colorful shading accent 5",
    "colorful list accent 5",
    "colorful grid accent 5",
    "light shading accent 6",
    "light list accent 6",
    "light grid accent 6",
    "medium shading 1 accent 6",
    "medium shading 2 accent 6",
    "medium list 1 accent 6",
    "medium list 2 accent 6",
    "medium grid 1 accent 6",
    "medium grid 2 accent 6",
    "medium grid 3 accent 6",
    "dark list accent 6",
    "colorful shading accent 6",
    "colorful list accent 6",
    "colorful grid accent 6",
    "subtle emphasis",
    "intense emphasis",
    "subtle reference",
    "intense reference",
    "book title",
    "bibliography",
    "toc heading",
    "plain table 1",
    "plain table 2",
    "plain table 3",
    "plain table 4",
    "plain table 5",
    "grid table light",
    "grid table 1 light",
    "grid table 2",
    "grid table 3",
    "grid table 4",
    "grid table 5 dark",
    "grid table 6 colorful",
    "grid table 7 colorful",
    "grid table 1 light accent 1",
    "grid table 2 accent 1",
    "grid table 3 accent 1",
    "grid table 4 accent 1",
    "grid table 5 dark accent 1",
    "grid table 6 colorful accent 1",
    "grid table 7 colorful accent 1",
    "grid table 1 light accent 2",
    "grid table 2 accent 2",
    "grid table 3 accent 2",
    "grid table 4 accent 2",
    "grid table 5 dark accent 2",
    "grid table 6 colorful accent 2",
    "grid table 7 colorful accent 2",
    "grid table 1 light accent 3",
    "grid table 2 accent 3",
    "grid table 3 accent 3",
    "grid table 4 accent 3",
    "grid table 5 dark accent 3",
    "grid table 6 colorful accent 3",
    "grid table 7 colorful accent 3",
    "grid table 1 light accent 4",
    "grid table 2 accent 4",
    "grid table 3 accent 4",
    "grid table 4 accent 4",
    "grid table 5 dark accent 4",
    "grid table 6 colorful accent 4",
    "grid table 7 colorful accent 4",
    "grid table 1 light accent 5",
    "grid table 2 accent 5",
    "grid table 3 accent 5",
    "grid table 4 accent 5",
    "grid table 5 dark accent 5",
    "grid table 6 colorful accent 5",
    "grid table 7 colorful accent 5",
    "grid table 1 light accent 6",
    "grid table 2 accent 6",
    "grid table 3 accent 6",
    "grid table 4 accent 6",
    "grid table 5 dark accent 6",
    "grid table 6 colorful accent 6",
    "grid table 7 colorful accent 6",
    "list table 1 light",
    "list table 2",
    "list table 3",
    "list table 4",
    "list table 5 dark",
    "list table 6 colorful",
    "list table 7 colorful",
    "list table 1 light accent 1",
    "list table 2 accent 1",
    "list table 3 accent 1",
    "list table 4 accent 1",
    "list table 5 dark accent 1",
    "list table 6 colorful accent 1",
    "list table 7 colorful accent 1",
    "list table 1 light accent 2",
    "list table 2 accent 2",
    "list table 3 accent 2",
    "list table 4 accent 2",
    "list table 5 dark accent 2",
    "list table 6 colorful accent 2",
    "list table 7 colorful accent 2",
    "list table 1 light accent 3",
    "list table 2 accent 3",
    "list table 3 accent 3",
    "list table 4 accent 3",
    "list table 5 dark accent 3",
    "list table 6 colorful accent 3",
    "list table 7 colorful accent 3",
    "list table 1 light accent 4",
    "list table 2 accent 4",
    "list table 3 accent 4",
    "list table 4 accent 4",
    "list table 5 dark accent 4",
    "list table 6 colorful accent 4",
    "list table 7 colorful accent 4",
    "list table 1 light accent 5",
    "list table 2 accent 5",
    "list table 3 accent 5",
    "list table 4 accent 5",
    "list table 5 dark accent 5",
    "list table 6 colorful accent 5",
    "list table 7 colorful accent 5",
    "list table 1 light accent 6",
    "list table 2 accent 6",
    "list table 3 accent 6",
    "list table 4 accent 6",
    "list table 5 dark accent 6",
    "list table 6 colorful accent 6",
    "list table 7 colorful accent 6",
    "mention",
    "smart hyperlink",
    "hashtag",
    "unresolved mention",
    "smart link",
]
