IMAGES:
  IMAGE_FORMAT: jpg
  IMAGE_HEIGHT: null
  IMAGE_WIDTH: null
  IMAGE_DPI: 90

DECOMPRESS_BOMB_CHECKS:
  MAX_DECOMPRESS_RATIO: 20
  MAX_IMAGE_PIXELS: 22369621

DOCUMENTS:
  MAX_DOC_BYTES: 10485760
  MAX_DOC_PAGES: 150

TIME_LIMITS:
  ANNOTATION_TIMEOUT_SECS: 180
  ANNOTATION_CLEANUP_SECS: 180

DATA_ORG:
  MAX_BYTES_IN_SHARD: 5368709120

LANGUAGES:
  TOP_K_LANGUAGES: 5

LIBREOFFICE:
  UNOSERVER_START_TIMEOUT: 60
  UNOCONVERT_TIMEOUT: 60
  SOFFICE_LAUNCH_TIMEOUT: 120
  SOFFICE_LAUNCH_PING_INTERVAL: 0.1

ENTITY_DEFINITION:
  MAX_HEADING_LEN: 150
  FORM_FIELD_MIN_LENGTH: 4

ENTITY_RELATIONS:
  BBOX_RELATION_OVERLAP_THRESHOLD: 0.45
  BBOX_RELATION_SCALE_THRESHOLD: 1.2
  BBOX_RELATION_CLOSENESS_THRESHOLD: 10
  WORD_2_ENTITY_OVERLAP_THRESHOLD: 0.8

ANNOTATION_FILTER:
  MIN_TEXT_CHARS: 200

